### ISSUE TITLE
Usage of StatDefOf

### ISSUE THREAD

**Issue by LecrisUT** [notfood/RimWorld-Outfitted#5]
I am a bit lost of what is the purpose of your `StatDefOf` of stats that are already available in vanilla Rimworld.
Are they initialized somewhere?

I primarily ask because in `SurvivalTools` mod I'm using an automatic patching method, and I'm searching for the `StatDefOf`s used in JobDrivers. You are using the same names as vanilla, and my patcher gets confused.

**Comment by notfood** [comment]
Huh... You'll conflict with a LOT of things if you are assuming xDefOf will be unique. It's used often in many mods. The usage is to only have it search the Def once on RW load, so you don't have to use `xDef.Named()`

**Comment by LecrisUT** [comment]
On my part it is intentional in order to catch any modded jobdrivers that use different stat definition but for the same kind of job. It's mostly to make mod compatibility easier.

Hmm I'm still a bit confused. Are the statdefs initialized somewhere in the code, because I couldn't find where. Wouldn't using the vanilla statdefof yield the same result?

**Comment by notfood** [comment]
It's the DefOf attribute, it's initializated by RimWorld itself. It shouldn't matter if you duplicate the ones in vanilla because it's merely a .Named() lookup.

**Comment by LecrisUT** [comment]
Playing around with your mod, now I understand why you included the duplicate `StatDefOf`. Perplexing why Tynan didn't include all of the vanilla `StatDefOf` to begin with.
